create database project1_db;
USE project1_db;
SHOW TABLES;

SELECT * FROM project1_customer;

#Questions:
-- Q1. What is the total revenue generated by male vs. female customers?
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- Q3. Which are the top 5 products with the highest average review rating?
-- Q4. Compare the average purchase amounts between Standard and Express shipping.
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
-- Q8. What are the top 3 most purchased products within each category?
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Q10. What is the revenue contribution of each age group?

-- 1.Revenue generated by each gender
SELECT gender,SUM(purchase_amount) as revenue_generated
FROM project1_customer
GROUP BY gender;

-- 2.customer used a discount but still paid more than average purchase amount
SELECT *
from project1_customer
WHERE purchase_amount>(SELECT avg(purchase_amount) FROM project1_customer) and discount_applied='Yes';

-- 3.Top 5 products with highest average review rating
SELECT item_purchased,ROUND(AVG(review_rating),2)
from project1_customer
Group by item_purchased
order by AVG(review_rating) DESC
LIMIT 5;

-- 4.Avg purchase amounts of standard and express shipping
SELECT shipping_type,AVG(purchase_amount)
FROM project1_customer
where shipping_type IN ('Express','Standard')
GROUP BY shipping_type;

-- 5.Avg spend and total revenue between subscribed and non subscribeds 
SELECT subscription_status as Subscribed,COUNT(customer_id),AVG(purchase_amount),SUM(purchase_amount)
FROM project1_customer
GROUP BY subscription_status;

-- 6.top 5 products having highest percentage of purchases with discount applied
SELECT item_purchased,
       ROUND(SUM(discount_applied = 'Yes') * 100 / COUNT(*), 2) AS discount_percentage
FROM project1_customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- 7.Differentiate customers into New,Returning,Loyal on previous purchases and count of each segment
SELECT * FROM project1_customer;
SELECT *,
	CASE
		WHEN previous_purchases>=10 THEN "Loyal"
        WHEN previous_purchases>1 THEN "Returning"
        ELSE "New"
	END AS status
FROM project1_customer;
SELECT status,COUNT FROM project1_customer GROUP BY status;

-- 8.Top 3 most purchased products within each category
WITH ranked as(
	SELECT category,item_purchased,COUNT(*) as total,
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM project1_customer
	group by category,item_purchased)
SELECT category,item_purchased,total FROM ranked
WHERE rn<=3
order by category,total DESC;

-- 9.Are customers who are repeat buyers(more than 5 previous purchases) likely to subscribe?
SELECT subscription_status as subscribed,COUNT(*) FROM  project1_customer
WHERE previous_purchases>5 
GROUP BY subscription_status;

-- 10.Revenue contibution of each group
SELECT Age_Group,SUM(purchase_amount) FROM project1_customer
group by Age_Group
